# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61f9df2cddfdc6dff10ad2c75de32075ac122a0ca34588889dd3daa8c4c8d6c4db590b2ac771304d72e2db4a89f53befd28098af1a2907d02f624c0bc7327768

test:
  secret_key_base: e104e3a282b23b10263b7184b011ddc120c3d20a99988f008a5c1bf827c2a9fbb414662ad7cc4d198686103bad0f622e7a32769661e32f3ea66c37b719318f8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
